org: jrgmonsalve
app: habi-property
service: habi-property
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: lambda.handler
    events:
      - httpApi:
          path: /property
          method: get

plugins:
  - serverless-offline
